### ISSUE TITLE
lang - Translate Error

### ISSUE THREAD

**Issue by Pet9948** [Darkhax-Minecraft/Open-Loader#10]
For some reason I cannot upload translation files. What could be the problem? Version: 1.16.5

I even did it with an example from the wiki: 

Placed files in: openloader\resources\Example\assets\tconstruct\lang\en_us.lang and nothing changes in the game.

**Comment by Darkhax** [comment]
Your language file is not correct. All versions of Minecraft supported by OpenLoader use json language files instead of .lang files. 

https://github.com/SlimeKnights/TinkersConstruct/blob/1.16/src/main/resources/assets/tconstruct/lang/en_us.json

**Comment by Pet9948** [comment]
Json has the same problem.
