### ISSUE TITLE
Datapack load order

### ISSUE THREAD

**Issue by Quizer9O8** [Darkhax-Minecraft/Open-Loader#12]
Some datapack from creators require to be sorted in such way that Datapack B comes before A. Due to the way Open-Loader handles datapacks we're unable to manually change the load order if needed. Therefore I would like to see an option to tell Open-Loader which datapacks should be loaded first.

**Comment by Darkhax** [comment]
The load order is handled by Vanilla and is a limitation of the datapack system. You should be able to use the in-game command to change load order as needed on a per-world basis.
