### ISSUE TITLE
Setting file path for resourcepacks and datapacks (Feature request)

### ISSUE THREAD

**Issue by captanredbeard** [Darkhax-Minecraft/Open-Loader#14]
Simply put. I would like to suggest a config option to change the location of the .minecraft openloader folder to another folder on the disk. The default would still remain .minecraft/openloader and .minecraft/config/openloader, but could be changed in the config.

Doing so would allow for storing resourcepacks and datapacks in a folder separate from the .minecraft instance, and allow for using datapacks not only over separate minecraft worlds, but also separate minecraft instances.

**Comment by Darkhax** [comment]
Thanks for the suggestion, this sounds like an interesting idea. I think the best way to implement this would be to allow a list of additional resource and data paths rather than replacing the default path completely.

**Comment by captanredbeard** [comment]
that's fine by me. Good luck. If there' anything I can do to help, feel free to ask,

**Comment by Darkhax** [comment]
This feature was implemented in https://github.com/Darkhax-Minecraft/Open-Loader/commit/cf5d7540cb06c64f7f142ab2bb0bd34bc19d915c
