### ISSUE TITLE
Question regarding the loading priority

### ISSUE THREAD

**Issue by alexmozaidze** [Darkhax-Minecraft/Open-Loader#15]
1) Are you planning to do something with load priority?
2) What options do we currently have to make make OpenLoader datapacks take priority?

**Comment by Darkhax** [comment]
> Are you planning to do something with load priority?

Mojang only offers two load priorities. TOP which loads later on, and BOTTOM which loads sooner. OpenLoader packs are given TOP priority by default but can be set to BOTTOM using the pack.mcmeta file.

> What options do we currently have to make make OpenLoader datapacks take priority?

The actual load order is determined on a per-world basis and is based on the order those packs were introduced into the world. When multiple packs are introduced at the same time it will use a combination of factors but is typically alphabetic order. The only way to change this order after it has been introduced to the world is to use Mojang's datapack command.

To further elaborate, imagine you have packs a, b, c and d. You load the world with only pack b and d causing the load order to be b then d. You then install pack a and c and load the world again, the new order will be b,d,a,c. If you load a completely new world however the order would be a,b,c,d.
