### ISSUE TITLE
not really an issue, just need help

### ISSUE THREAD

**Issue by BrayDoesStuffYT** [Darkhax-Minecraft/Open-Loader#22]
how do i get the datapacks that open loader downloads, i want to download some of them

**Comment by Darkhax** [comment]
OpenLoader is primarily intended for sharing datapacks you make yourself as part of a modpack. CurseForge has [this project category](https://www.curseforge.com/minecraft/texture-packs/data-packs), however many of these projects are mislabled and are not actually datapacks. 

The [Vanilla Tweaks](https://vanillatweaks.net/picker/datapacks/) project has a pretty extensive list of datapacks they have made which should all be compatible with OpenLoader. There is also the [Terralith pack](https://www.planetminecraft.com/data-pack/terralith-overworld-evolved-100-biomes-caves-and-more/) which adds many new biomes to the game. I believe they have a few other packs on their website as well.
