### ISSUE TITLE
Feature Request: Load Datapacks Before JER Loads

### ISSUE THREAD

**Issue by puncrafter** [Darkhax-Minecraft/Open-Loader#25]
At least in the 1.16.5 version, the one that I'm using, Just Enough Resources loads before Open Loader is able to load the datapacks, which causes any alterations to the loot tables to not be reflected in-game. I don't actually know if it's possible to fix this on your end, but I figured I'd post the issue anyways.

**Comment by Darkhax** [comment]
Unfortunately I don't think I have any control over this.
