### ISSUE TITLE
[SUGGESTION]`/openloader` commands that opens the openloader directory from minecraft

### ISSUE THREAD

**Issue by thelegitdolt** [Darkhax-Minecraft/Open-Loader#27]
Crafttweaker has a `/ct script` command that automatically opens the scripts directory from your minecraft folder. This saves a lot of time for modpack devs as they no longer have to scroll out of their minecraft and navigate to the exact folders needed. This would also be a pretty cool feature for openloader in my opinion!!! Thanks for listening

**Comment by Darkhax** [comment]
Thanks for the suggestion, this sounds like a great idea.
