### ISSUE TITLE
[FEEDBACK] Previous versions of resource-packs used the term built-in and not (OpenLoader) next to it.

### ISSUE THREAD

**Issue by seriousfreezing** [Darkhax-Minecraft/Open-Loader#34]
### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Feedback

I was wondering if it was possible to revert this change, since in the 1.19.2 versions there is no term "(OpenLoader)" but rather (built-in).

I'd also like to know if there's a way to hide the resource packs and datapacks inside the OpenLoader.

**Comment by Darkhax** [comment]
Hello, thank you for the feedback. Sorry for taking so long to get back to you on this. Mojang changed how pack sources are handled in this version and our source now adds OpenLoader and makes the name green. This is useful for debugging issues but I can understand why you may want to hide this information. I've pushed an update that adds the `displaySourceName` option which will let you disable this. The files are currently being processed by CurseForge and will hopefully be available soon.

**Comment by seriousfreezing** [comment]
In the case of this update, it just goes back to the way it was before, does it? Do you have any options to customize it, like changing the name or things like that? Or even how to hide the built-in resource pack?

**Comment by Darkhax** [comment]
No, this config option will only remove the source name from entries loaded by open loader.

**Comment by seriousfreezing** [comment]
Ok, thanks!
