### ISSUE TITLE
[FEEDBACK] Update for 1.20.6?

### ISSUE THREAD

**Issue by seriousfreezing** [Darkhax-Minecraft/Open-Loader#36]
### Minecraft Version

1.20.6

### Mod Loader

Fabric

### Feedback

.

**Comment by Darkhax** [comment]
Hello, thank you for your interest in this project. I will be porting to 1.20.5 and 1.20.6 however I am delaying these updates to focus on improving my projects. This will hopefully be done before 1.21 comes out but this is not a strict timeline.

**Comment by seriousfreezing** [comment]
It's okay! No rush!
