### ISSUE TITLE
Is it possible to change the load order every since a world will be loaded?

### ISSUE THREAD

**Issue by cyberpunkbln** [Darkhax-Minecraft/Open-Loader#5]
Hello,

is it possible to to change the load order every since a world will be loaded and every datapack in openloader/data will be loaded as last datapack?

At this time im must move all datapacks out from openloader/data, load the world, close the world and the move the datapacks back and load the world again.

thx

Edit: I mean when i install new mods, this mods became the loading order last, after the first init from openloader with the state of mods at this time.

**Comment by Darkhax** [comment]
Hello, unfortunately there is no good/easy way. Mojang has a datapack command which allows you to move them but there is no automatic way to do this.
