### ISSUE TITLE
Impossible to assign "forge:" tag

### ISSUE THREAD

**Issue by JWTHDYTWA** [Darkhax-Minecraft/Open-Loader#7]
If you put datapack with such structure:
` datapack_name\data\forge\tags\items\plates\gold.json `
It will be impossible to load a world.
But if you override `forge` with something else, your `custom_namespace`, everything will be ok.

**Comment by JWTHDYTWA** [comment]
Here is .json format:
[gold.json](https://gist.github.com/JWTHDYTWA/ecaa907dfe4a5dfd2b2b429a485f999b)

**Comment by Darkhax** [comment]
Hello, could you share a log file for a world that could not load?

**Comment by JWTHDYTWA** [comment]
Where should this log file be?

**Comment by JWTHDYTWA** [comment]
Default logs in `.minecraft\logs` are only generated on startup.
This is what i see after world loading attempt:
![изображение](https://user-images.githubusercontent.com/30724185/101485870-61918c80-398e-11eb-9ee0-22ca17340d64.png)

**Comment by JWTHDYTWA** [comment]
Don't mind it, the problem was More Plates mod.
It removes all items from tags but its own.
